# -*- coding: utf-8 -*-
"""Record.json

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aJK-gbyYB-ShuQhxAaBGVZgz1X5-NAD
"""

record={1:{"name":'ishika',"cgpa":89},
        2:{"name":'pooja',"cgpa":99},
        3:{"name":'saksham',"cgpa":110}}
print(record)

print(record[1])

print(record[1]['cgpa'])

"""# New section"""

import json

js=json.dumps(record)

js

type(js)

fd=open("record.json","w")

fd.write(js)

fd.close()

fd=open("record.json","r")

txt=fd.read()

fd.close()

import time

time.ctime()

type(record)